// Package artifact defines Bebop's persistent, reviewable saved-plan contract.
package artifact

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/bebop-home/bebop/internal/buildinfo"
	"github.com/bebop-home/bebop/internal/config"
	"github.com/bebop-home/bebop/internal/errs"
	"github.com/bebop-home/bebop/internal/facts"
	"github.com/bebop-home/bebop/internal/plan"
	"github.com/bebop-home/bebop/internal/services"
	"github.com/bebop-home/bebop/internal/target"
)

const SchemaVersion = 1

// Artifact is deliberately a stable data contract rather than a dump of a CLI
// result. Its self-fingerprint covers every field except Fingerprint itself.
// Apply regenerates the Plan from fresh facts and never executes this JSON's
// scripts directly.
type Artifact struct {
	SchemaVersion            int              `json:"schema_version"`
	BebopVersion             string           `json:"bebop_version"`
	HostAlias                string           `json:"host_alias,omitempty"`
	Target                   string           `json:"target"`
	ConfigPath               string           `json:"config_path,omitempty"`
	Config                   config.Config    `json:"config"`
	ConfigFingerprint        string           `json:"config_fingerprint"`
	ServiceInputs            []services.Input `json:"service_inputs,omitempty"`
	ServiceInputsFingerprint string           `json:"service_inputs_fingerprint,omitempty"`
	HostIdentity             facts.Identity   `json:"host_identity"`
	ObservedStateFingerprint string           `json:"observed_state_fingerprint"`
	Plan                     plan.Plan        `json:"plan"`
	Fingerprint              string           `json:"fingerprint"`
}

type canonicalArtifact struct {
	SchemaVersion            int              `json:"schema_version"`
	BebopVersion             string           `json:"bebop_version"`
	HostAlias                string           `json:"host_alias,omitempty"`
	Target                   string           `json:"target"`
	ConfigPath               string           `json:"config_path,omitempty"`
	Config                   config.Config    `json:"config"`
	ConfigFingerprint        string           `json:"config_fingerprint"`
	ServiceInputs            []services.Input `json:"service_inputs,omitempty"`
	ServiceInputsFingerprint string           `json:"service_inputs_fingerprint,omitempty"`
	HostIdentity             facts.Identity   `json:"host_identity"`
	ObservedStateFingerprint string           `json:"observed_state_fingerprint"`
	Plan                     plan.Plan        `json:"plan"`
}

func New(alias, configPath string, current target.Target, desired config.Config, host facts.HostFacts, result plan.Plan) (Artifact, error) {
	configFingerprint, err := config.Fingerprint(desired)
	if err != nil {
		return Artifact{}, err
	}
	observedFingerprint, err := host.ConvergenceFingerprint()
	if err != nil {
		return Artifact{}, err
	}
	serviceInputsFingerprint, serviceInputs, err := services.InputsFingerprint(desired)
	if err != nil {
		return Artifact{}, err
	}
	if err := validateServiceActions(result, serviceInputs); err != nil {
		return Artifact{}, err
	}
	artifact := Artifact{
		SchemaVersion: SchemaVersion, BebopVersion: buildinfo.Version, HostAlias: alias,
		Target: current.String(), ConfigPath: configPath, Config: desired,
		ConfigFingerprint: configFingerprint, ServiceInputs: serviceInputs, ServiceInputsFingerprint: serviceInputsFingerprint, HostIdentity: host.Identity(),
		ObservedStateFingerprint: observedFingerprint, Plan: result,
	}
	if err := artifact.Finalize(); err != nil {
		return Artifact{}, err
	}
	return artifact, nil
}

func (artifact Artifact) CanonicalJSON() ([]byte, error) {
	return json.Marshal(canonicalArtifact{
		SchemaVersion: artifact.SchemaVersion, BebopVersion: artifact.BebopVersion,
		HostAlias: artifact.HostAlias, Target: artifact.Target, ConfigPath: artifact.ConfigPath,
		Config: artifact.Config, ConfigFingerprint: artifact.ConfigFingerprint, ServiceInputs: artifact.ServiceInputs, ServiceInputsFingerprint: artifact.ServiceInputsFingerprint,
		HostIdentity: artifact.HostIdentity, ObservedStateFingerprint: artifact.ObservedStateFingerprint,
		Plan: artifact.Plan,
	})
}

func (artifact *Artifact) Finalize() error {
	canonical, err := artifact.CanonicalJSON()
	if err != nil {
		return err
	}
	sum := sha256.Sum256(canonical)
	artifact.Fingerprint = hex.EncodeToString(sum[:])
	return nil
}

func (artifact Artifact) Verify() error {
	if artifact.SchemaVersion != SchemaVersion {
		return errs.New(errs.PlanInvalid, fmt.Sprintf("unsupported Bebop plan schema version %d (this binary supports %d)", artifact.SchemaVersion, SchemaVersion), nil)
	}
	if artifact.BebopVersion != buildinfo.Version {
		return errs.New(errs.PlanInvalid, fmt.Sprintf("plan was generated by Bebop %s but this binary is %s", artifact.BebopVersion, buildinfo.Version), nil)
	}
	if _, err := target.Parse(artifact.Target); err != nil {
		return errs.New(errs.PlanInvalid, "plan contains an invalid target", err)
	}
	if err := config.Validate(artifact.Config); err != nil {
		return errs.New(errs.PlanInvalid, "plan contains invalid desired configuration", err)
	}
	configFingerprint, err := config.Fingerprint(artifact.Config)
	if err != nil {
		return err
	}
	if artifact.ConfigFingerprint != configFingerprint {
		return errs.New(errs.PlanTampered, "plan configuration fingerprint does not match its configuration", nil)
	}
	serviceInputsFingerprint, err := services.FingerprintInputs(artifact.ServiceInputs)
	if err != nil {
		return errs.New(errs.PlanInvalid, "plan contains invalid service input metadata", err)
	}
	if artifact.ServiceInputsFingerprint != serviceInputsFingerprint {
		return errs.New(errs.PlanTampered, "plan service input fingerprint does not match its input metadata", nil)
	}
	if len(artifact.Config.Services) != len(artifact.ServiceInputs) {
		return errs.New(errs.PlanTampered, "plan service inputs do not match its desired configuration", nil)
	}
	if err := validateServiceActions(artifact.Plan, artifact.ServiceInputs); err != nil {
		return errs.New(errs.PlanTampered, "plan service actions do not match input metadata", err)
	}
	planFingerprint, err := fingerprintPlan(artifact.Plan)
	if err != nil {
		return errs.New(errs.PlanInvalid, "cannot canonicalize plan", err)
	}
	if artifact.Plan.Fingerprint == "" || artifact.Plan.Fingerprint != planFingerprint {
		return errs.New(errs.PlanTampered, "plan fingerprint does not match its ordered actions", nil)
	}
	if artifact.Plan.Target != artifact.Target {
		return errs.New(errs.PlanTampered, "plan target does not match artifact target", nil)
	}
	canonical, err := artifact.CanonicalJSON()
	if err != nil {
		return errs.New(errs.PlanInvalid, "cannot canonicalize plan artifact", err)
	}
	sum := sha256.Sum256(canonical)
	if artifact.Fingerprint == "" || artifact.Fingerprint != hex.EncodeToString(sum[:]) {
		return errs.New(errs.PlanTampered, "plan artifact fingerprint mismatch", nil)
	}
	return nil
}

func validateServiceActions(result plan.Plan, inputs []services.Input) error {
	byName := make(map[string]services.Input, len(inputs))
	for _, input := range inputs {
		byName[input.Name] = input
	}
	for _, change := range result.Changes {
		if change.Module != "services" {
			continue
		}
		input, exists := byName[change.Action.Resource]
		if !exists || change.Action.Resource == "" {
			return fmt.Errorf("unknown service resource %q", change.Action.Resource)
		}
		if change.Action.Kind == "service.remove" {
			continue
		}
		if change.Action.Kind != "service.deploy" && change.Action.Kind != "service.start" && change.Action.Kind != "service.stop" {
			return fmt.Errorf("unknown service action %q", change.Action.Kind)
		}
		if change.Action.SourceDigest != input.SourceDigest || change.Action.InputFingerprint != input.InputFingerprint || change.Action.SecretFingerprint != input.SecretFingerprint {
			return fmt.Errorf("service action %q does not match input fingerprint", change.ID)
		}
	}
	return nil
}

func fingerprintPlan(result plan.Plan) (string, error) {
	canonical, err := result.CanonicalJSON()
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(canonical)
	return hex.EncodeToString(sum[:]), nil
}

func Decode(reader io.Reader) (Artifact, error) {
	decoder := json.NewDecoder(reader)
	decoder.DisallowUnknownFields()
	var artifact Artifact
	if err := decoder.Decode(&artifact); err != nil {
		return Artifact{}, errs.New(errs.PlanInvalid, "invalid plan artifact", err)
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		if err == nil {
			return Artifact{}, errs.New(errs.PlanInvalid, "plan artifact contains multiple JSON values", nil)
		}
		return Artifact{}, errs.New(errs.PlanInvalid, "invalid trailing plan artifact data", err)
	}
	if err := artifact.Verify(); err != nil {
		return Artifact{}, err
	}
	return artifact, nil
}

func LoadFile(filename string) (Artifact, error) {
	file, err := os.Open(filename)
	if err != nil {
		return Artifact{}, errs.New(errs.PlanInvalid, "cannot read plan artifact", err)
	}
	defer file.Close()
	return Decode(file)
}

func WriteFile(filename string, artifact Artifact) error {
	if err := artifact.Verify(); err != nil {
		return err
	}
	encoded, err := json.MarshalIndent(artifact, "", "  ")
	if err != nil {
		return fmt.Errorf("encode plan artifact: %w", err)
	}
	encoded = append(encoded, '\n')
	directory := filepath.Dir(filename)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create plan artifact directory: %w", err)
	}
	temporary, err := os.CreateTemp(directory, ".bebop-plan-*")
	if err != nil {
		return fmt.Errorf("create temporary plan artifact: %w", err)
	}
	temporaryName := temporary.Name()
	defer os.Remove(temporaryName)
	if err := temporary.Chmod(0o600); err != nil {
		temporary.Close()
		return fmt.Errorf("set plan artifact permissions: %w", err)
	}
	if _, err := temporary.Write(encoded); err != nil {
		temporary.Close()
		return fmt.Errorf("write plan artifact: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		temporary.Close()
		return fmt.Errorf("sync plan artifact: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close plan artifact: %w", err)
	}
	if err := os.Rename(temporaryName, filename); err != nil {
		return fmt.Errorf("replace plan artifact atomically: %w", err)
	}
	return nil
}
